site_name: ThinkingCity
site_url: https://github.com/telefonicaid/thinkingcity/
repo_url: https://github.com/telefonicaid/thinkingcity
site_description: ThinkingCity platform document site
docs_dir: docs/
site_dir: html
edit_uri: edit/master/docs/
markdown_extensions: [toc,tables, fenced_code]
extra_css: ["css/style.css" ]
use_directory_urls: false
theme: readthedocs
nav:
  - 'Introduction': 'index.md'
  - 'APIs':
    - 'Authentication API': 'authentication_api.md'
    - 'Authorization with grants API': 'authorization_api.md'
    - 'Device API': 'device_api.md'
    - 'Data API': 'data_api.md'
    - 'Complex Event Processing API': 'cep_api.md'
    - 'Management API': 'management_api.md'
  - 'Multitenancy: Service and Subservice': 'multitenancy.md'
  - 'Data persistence':
    - 'Naming conventions': 'naming_conventions.md'
  - 'Architecture':
    - 'FIWARE Components': 'walkthrough.md'
    - 'IoT Agents (IoTA)': 'device_gateway.md'
    - 'Context Broker (Orion)': 'context_broker.md'
    - 'Connector Framework (Cygnus)': 'cygnus.md'
    - 'Complex Event Processing (Perseo)': 'cep.md'
    - 'Security Components (IDM, PEP, AC)': 'security.md'
  - 'Topics':
    - 'Big Data streaming with MongoDB': 'topics/bigdata_streaming_mongodb.md'
    - 'Character set limitations': 'topics/character_set_limitations.md'
    - 'How to send notifications': 'topics/how_notifications_work.md'
    - 'Geolocalized entities': 'topics/geolocalized_entities.md'
    - 'Subscriptions': 'topics/subcriptions.md'
    - 'Performance considerations': 'topics/performance_considerations.md'
    - 'Tips on how to model project entities': 'topics/modelling_considerations.md'
    - 'Quick start on device connection to the platform (with Ultralight 2.0)': 'topics/device_connection.md'
    - 'What is the best way to calculate a value based on Context changes': 'topics/data_calculation.md'
    - 'How to massively move data from/to the platform (Big Data)': 'topics/move_big_data.md'
    - 'Users and Permissions': 'topics/user_permissions.md'
    - 'Which historical backend must I use?': 'topics/which_historical_backend.md' 
    - 'How to add new actions to CEP': 'topics/cep_new_actions.md'
